### ISSUE TITLE
Pages of bulk market orders have different expiration time.

### ISSUE THREAD

**Issue by drevken** [ccpgames/esi-issues#487]
Pages of bulk market orders have different expiration time.

A typical example:
I access /markets/10000002/orders/ which has 27 pages usually.
pages 1-2: access time 14:45 GMT, expiration in header shows 14:42 GMT, i.e. I receive page that has already expired
pages 3-4: access time 14:45 GMT, expiration shows 14:46 - correct behavior
pages 5,7,8,10,11-14,16-21, 23-25, 27 show expiration time of 14:42, i.e. already expired
pages 6,9,15,... show 14:46

I think it's related to this issue: https://github.com/ccpgames/esi-issues/issues/194

**Comment by aquarhead** [comment]
Just to double check:

![image](https://user-images.githubusercontent.com/222272/28025401-d66508ea-6582-11e7-9b3e-583b0a3af94b.png)

- `Date` is when response is generated
- `Expires` is when the cache should expire
-  `Last-Modified` is when the cached content is generated

Are you seeing cases where `Date` > `Expires` ?

**Comment by drevken** [comment]
Yes, e.g.:

date: Mon, 10 Jul 2017 14:52:53 GMT
expires: Mon, 10 Jul 2017 14:51:38 GMT
last-modified: Mon, 10 Jul 2017 14:46:38 GMT

And I see them consistently, basically every time I access 27 pages of Forge data, more than half of them have Date>Expires.
I then request these pages again after a minute, and some of them are update, but some again have Date>Expires. Sometimes I can acquire the full set of 27 pages with the same cache time using this "technique". But more often I end up with just a subset of 27 pages.

**Comment by mullinger** [comment]
I am starting to pull all orders universe wide as well now and had intended to adhere to the expiry times in the headers.
My implementation currently uses the last pages expiry for the next refresh of the whole region.

Due to the problem described above this refreshes FAR more often (especially orders show be cached for 300 secs) and possibly inconsistent(?)

**Comment by sloveridge** [comment]
I am also seeing this issue. It is making it difficult (and sometimes impossible) to get a consistent view of the data at a point in time.

For instance walking through the pages and retrying any that do not have the highest last modified time can produce something like the following:

Page: 1 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:53:24
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:48:48
Page: 3 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:53:24
Page: 4 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:48:48
Page: 5 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:53:24
Page: 6 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:53:24
Page: 7 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:53:24
Page: 8 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:53:24
Page: 9 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:48:59 Expires: 2017-08-26 16:53:24
Page: 10 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:35 Expires: 2017-08-26 16:53:24
Page: 11 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:52 Expires: 2017-08-26 16:53:24
Page: 12 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:50:01 Expires: 2017-08-26 16:48:48
Page: 13 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:03 Expires: 2017-08-26 16:53:24
Page: 14 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:05 Expires: 2017-08-26 16:53:24
Page: 15 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:06 Expires: 2017-08-26 16:53:24
Page: 16 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:06 Expires: 2017-08-26 16:53:24
Page: 17 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:06 Expires: 2017-08-26 16:53:24
Page: 18 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:07 Expires: 2017-08-26 16:53:24
Page: 19 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:07 Expires: 2017-08-26 16:53:24
Page: 20 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:09 Expires: 2017-08-26 16:53:24
Page: 21 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:24 Expires: 2017-08-26 16:53:24
Page: 22 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:35 Expires: 2017-08-26 16:53:24
Page: 23 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:35 Expires: 2017-08-26 16:53:24
Page: 24 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:37 Expires: 2017-08-26 16:53:24
Page: 25 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:37 Expires: 2017-08-26 16:53:24
Page: 26 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:37 Expires: 2017-08-26 16:53:24
Page: 27 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:49:21 Expires: 2017-08-26 16:53:24
Page: 28 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:38 Expires: 2017-08-26 16:53:24
Page: 29 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:50:38 Expires: 2017-08-26 16:53:24
Retrying pages: [2, 4, 12]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:00 Expires: 2017-08-26 16:48:48
Page: 4 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:00 Expires: 2017-08-26 16:48:48
Page: 12 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:00 Expires: 2017-08-26 16:48:48
Retrying pages: [2, 4, 12]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:11 Expires: 2017-08-26 16:48:48
Page: 4 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:11 Expires: 2017-08-26 16:48:48
Page: 12 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:11 Expires: 2017-08-26 16:48:48
Retrying pages: [2, 4, 12]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:22 Expires: 2017-08-26 16:48:48
Page: 4 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:22 Expires: 2017-08-26 16:48:48
Page: 12 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:22 Expires: 2017-08-26 16:48:48
Retrying pages: [2, 4, 12]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:33 Expires: 2017-08-26 16:48:48
Page: 4 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:33 Expires: 2017-08-26 16:48:48
Page: 12 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:33 Expires: 2017-08-26 16:48:48
Retrying pages: [2, 4, 12]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:44 Expires: 2017-08-26 16:48:48
Page: 4 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:51:46 Expires: 2017-08-26 16:53:24
Page: 12 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:44 Expires: 2017-08-26 16:48:48
Retrying pages: [2, 12]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:51:54 Expires: 2017-08-26 16:48:48
Page: 12 Last Modified: 2017-08-26 16:48:24 Date: 2017-08-26 16:51:57 Expires: 2017-08-26 16:53:24
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:01 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:05 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:10 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:14 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:18 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:22 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:26 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:30 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:34 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:38 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:43 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:47 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:51 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:55 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:52:59 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:43:48 Date: 2017-08-26 16:53:04 Expires: 2017-08-26 16:48:48
Retrying pages: [2]
Page: 2 Last Modified: 2017-08-26 16:53:00 Date: 2017-08-26 16:53:10 Expires: 2017-08-26 16:58:00

In this instance initially there were 3 pages that had a last modified older than the extraction time with 4 and then 12 being updated after retrying. The data for the 2017-08-26 16:48:24 however, was never available with page 2 skipping it and going straight to 2017-08-26 16:53:00.

**Comment by lukasni** [comment]
Hitting the same problem, Redis apparently isn't happy with negative expire times. I'm setting them to `Date + 300s` for now, but as mentioned above, that leads to weird behavior on refresh, where some pages will be pulled from cache while others are already invalidated.

**Comment by zweizeichen** [comment]
There's all kinds of fun things going on with the market data. Try 

> docker run -ti -e LOG_LEVEL=debug -e CLIENT_ID=YOURESICLIENTID -e SECRET_KEY=YOURESISECRETKEY -e REFRESH_TOKEN=YOURREFRESHTOKEN evetools/market-streamer

wait a couple of seconds and see the output (no worries it does not upload any data). For example pages seem to regularily overlap and there are typeIDs which should not be on the market and so on. The code can be found over at [EVE-Tools/market-streamer](https://github.com/EVE-Tools/market-streamer).

**Comment by lukasni** [comment]
Adding on to @zweizeichen, definitely seeing overlap. Here is an example for Jita:
```python
>>> len(orders)
255516
>>> len(set([o['order_id'] for o in orders]))
255459
```

As you can see in the following, this is likely still related to the caching issues, as some of those pages have expire dates older than the creation date:
```Page 02:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 03:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 04:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 05:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 06:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 07:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 08:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 09:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 10:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 11:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 12:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 13:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 14:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 15:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 16:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 17:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 18:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 19:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 20:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 21:	Date Fri, 15 Sep 2017 07:47:03 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 22:	Date Fri, 15 Sep 2017 07:47:05 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 23:	Date Fri, 15 Sep 2017 07:47:17 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 24:	Date Fri, 15 Sep 2017 07:47:18 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 25:	Date Fri, 15 Sep 2017 07:47:19 GMT,	Expires Fri, 15 Sep 2017 07:46:03 GMT
Page 26:	Date Fri, 15 Sep 2017 07:47:20 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT
Page 27:	Date Fri, 15 Sep 2017 07:47:20 GMT,	Expires Fri, 15 Sep 2017 07:50:40 GMT```

**Comment by aquarhead** [comment]
I'm going to add some debug logging to root out problems within ESI

**Comment by lukasni** [comment]
Let me know if you need any additional details from this end.

**Comment by a-tal** [comment]
that was an autoclose via commit. still need to test this, but pretty sure this bug has been squashed.

**Comment by sloveridge** [comment]
Is this in the https://esi.tech.ccp.is/dev/ API at the moment?

I can also test if so.

**Comment by a-tal** [comment]
not quite yet. I just pushed the code to github

**Comment by a-tal** [comment]
merged. building now

**Comment by sloveridge** [comment]
Thank you. 

I just did a test and still the same problem so I assume it is not in the dev API yet.

Let us know when it is =)

**Comment by a-tal** [comment]
this is live in production now. the current cache cycles will need to expire before the change will be noticed.

thanks to everyone who provided detailed logs leading to this fix
