### ISSUE TITLE
All DELETE Contacts returning `Unhandled internal error encountered!` from ESI

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#692]
# Bug
DELETE Contacts returning `Unhandled internal error encountered!`
### Request
Deleting the following contacts from at least two characters.
98299856   
98531259   
98533055   

### Response
500 Internal Server Error, Body: {"error":"Unhandled internal error encountered!"}

### Expected
Not a 500 error

Will PM Further details if needed.

**Comment by antihax** [comment]
This now appears to be affecting all of my delete contact calls for ~600 tokens.

**Comment by ccp-zoetrope** [comment]
This should be fixed now. Pay attention that the /v2/ endpoint that got promoted to latest on December 20th has you pass in contact_id's through query parameters and not in the body. Let me know if it's working for you though.

**Comment by antihax** [comment]
Still broken.

```2018/01/03 00:57:54 contactSync.go:183: Status: 500 Internal Server Error, Body: {"error":"Unhandled internal error encountered!"}```

![image](https://user-images.githubusercontent.com/6982107/34506088-64ff2a12-efef-11e7-88a7-10e6e0794725.png)

**Comment by ccp-zoetrope** [comment]
This was still failing because there was an internal limit on the EVE side of things not allowing it to pass in 100 contacts at a time. This endpoint has a maxItems amount of 20 IDs and should be working now. I'm going to wait until I get confirmation to close this issue though :)

**Comment by antihax** [comment]
Appears to be working.

![image](https://user-images.githubusercontent.com/6982107/34545509-0f5fae78-f0b3-11e7-9939-c01ae8f33504.png)

**Comment by ccp-zoetrope** [comment]
![](https://max-media.imgix.net/transfers/2015/12/31/26299216fbf1f09f630fe96a1bc466ae84a79562.gif)
